on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
name: Build Semgrep image with Scripts
jobs:
  Build:
    name: build-semgrep-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/semgrep-with-sarif-transform:latest
          